import { useEffect } from 'react'
import { useEditorStore } from '../editor/store'
import type { Clip } from '../editor/types'

type Point={x:number;y:number}
type Box={left:number;top:number;width:number;height:number}
const HANDLE_CLASS='fx-transform-handle'
const HANDLE_DIRS=['nw','n','ne','e','se','s','sw','w'] as const
function activeVisualClips():Clip[]{const{project}=useEditorStore.getState();return project.clips.filter(c=>c.track!=='audio'&&project.playhead>=c.start&&project.playhead<c.start+c.duration).sort((a,b)=>b.trackIndex-a.trackIndex)}
function endOfProject(){const{project}=useEditorStore.getState();return Math.max(0,...project.clips.map(c=>c.start+c.duration))}
function isTextClip(clip:Clip,layer?:HTMLElement){return !!layer?.querySelector('.fx-text-preview')||clip.name==='Título'||clip.name==='Subtítulo'||clip.name.toLowerCase().startsWith('texto')}
function applyTextStyle(layer:HTMLElement,clip:Clip){const text=layer.querySelector<HTMLElement>('.fx-text-preview');if(!text)return;text.textContent=clip.text??clip.name;text.style.color=clip.textColor??'#ffffff';text.style.fontSize=`${clip.fontSize??64}px`;text.style.fontFamily=clip.fontFamily??'Arial, sans-serif';text.style.fontWeight=String(clip.fontWeight??700);text.style.width='100%';text.style.height='100%';text.style.display='flex';text.style.alignItems='center';text.style.justifyContent='center';text.style.textAlign='center';text.style.pointerEvents='auto';text.contentEditable='false'}
function ensureHandles(layer:HTMLElement,clip:Clip){if(layer.querySelectorAll<HTMLElement>(`.${HANDLE_CLASS}`).length===HANDLE_DIRS.length)return;layer.querySelectorAll(`.${HANDLE_CLASS}`).forEach(h=>h.remove());HANDLE_DIRS.forEach(dir=>{const el=document.createElement('div');el.className=`${HANDLE_CLASS} ${HANDLE_CLASS}-${dir}`;el.style.position='absolute';el.style.width='10px';el.style.height='10px';el.style.margin='-5px';el.style.borderRadius='3px';el.style.background='#fff';el.style.border='2px solid #7c5cff';el.style.boxSizing='border-box';el.style.zIndex='1000';el.style.pointerEvents='auto';el.style.cursor=dir==='n'||dir==='s'?'ns-resize':dir==='e'||dir==='w'?'ew-resize':dir==='ne'||dir==='sw'?'nesw-resize':'nwse-resize';Object.assign(el.style,({nw:{left:'0%',top:'0%'},n:{left:'50%',top:'0%'},ne:{left:'100%',top:'0%'},e:{left:'100%',top:'50%'},se:{left:'100%',top:'100%'},s:{left:'50%',top:'100%'},sw:{left:'0%',top:'100%'},w:{left:'0%',top:'50%'}} as Record<string,Partial<CSSStyleDeclaration>>)[dir]);el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();startResize(e,clip,dir)});layer.appendChild(el)})}
function startResize(event:PointerEvent,clip:Clip,dir:typeof HANDLE_DIRS[number]){const canvas=document.querySelector<HTMLElement>('.fx-canvas');if(!canvas)return;const rect=canvas.getBoundingClientRect();const start:Box={left:clip.x,top:clip.y,width:clip.width,height:clip.height};const origin:Point={x:event.clientX,y:event.clientY};const move=(ev:PointerEvent)=>{const dx=(ev.clientX-origin.x)/rect.width*100,dy=(ev.clientY-origin.y)/rect.height*100;let left=start.left,top=start.top,width=start.width,height=start.height;if(dir.includes('e'))width=start.width+dx;if(dir.includes('w')){left=start.left+dx;width=start.width-dx}if(dir.includes('s'))height=start.height+dy;if(dir.includes('n')){top=start.top+dy;height=start.height-dy}if(width<2){width=2;if(dir.includes('w'))left=start.left+start.width-2}if(height<2){height=2;if(dir.includes('n'))top=start.top+start.height-2}useEditorStore.getState().updateClip(clip.id,{x:Number(left.toFixed(2)),y:Number(top.toFixed(2)),width:Number(width.toFixed(2)),height:Number(height.toFixed(2))})};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function bindLayerMovement(layer:HTMLElement,clip:Clip){if(layer.dataset.transformBound===clip.id)return;layer.dataset.transformBound=clip.id;layer.addEventListener('pointerdown',event=>{const target=event.target as HTMLElement;if(target.closest(`.${HANDLE_CLASS}`))return;if(!target.closest('video, img, .fx-text-preview'))return;event.preventDefault();event.stopPropagation();useEditorStore.getState().selectClip(clip.id);const canvas=document.querySelector<HTMLElement>('.fx-canvas');if(!canvas)return;const rect=canvas.getBoundingClientRect();const origin={x:event.clientX,y:event.clientY},start={x:clip.x,y:clip.y};const move=(ev:PointerEvent)=>{const dx=(ev.clientX-origin.x)/rect.width*100,dy=(ev.clientY-origin.y)/rect.height*100;useEditorStore.getState().updateClip(clip.id,{x:Number((start.x+dx).toFixed(2)),y:Number((start.y+dy).toFixed(2))})};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)})}
export default function PreviewInteractionController(){const project=useEditorStore(s=>s.project),selectedClipId=useEditorStore(s=>s.selectedClipId);useEffect(()=>{const sync=()=>{const end=endOfProject();const current=useEditorStore.getState().project;if(current.isPlaying&&end>0&&current.playhead>=end-.05){useEditorStore.getState().setPlayhead(end);useEditorStore.getState().setPlaying(false)}const clips=activeVisualClips();Array.from(document.querySelectorAll<HTMLElement>('.fx-layer')).forEach((layer,index)=>{const clip=clips[index];if(!clip)return;layer.style.zIndex=isTextClip(clip,layer)?'999':'auto';if(isTextClip(clip,layer))applyTextStyle(layer,clip);bindLayerMovement(layer,clip);if(selectedClipId===clip.id)ensureHandles(layer,clip);else layer.querySelectorAll(`.${HANDLE_CLASS}`).forEach(h=>h.remove())})};const id=window.setTimeout(sync,0);return()=>window.clearTimeout(id)},[project.playhead,project.isPlaying,project.clips,selectedClipId]);useEffect(()=>{const observer=new MutationObserver(()=>window.setTimeout(()=>{const clips=activeVisualClips();Array.from(document.querySelectorAll<HTMLElement>('.fx-layer')).forEach((layer,index)=>{const clip=clips[index];if(!clip)return;layer.style.zIndex=isTextClip(clip,layer)?'999':'auto';if(isTextClip(clip,layer))applyTextStyle(layer,clip);bindLayerMovement(layer,clip);if(useEditorStore.getState().selectedClipId===clip.id)ensureHandles(layer,clip)})},0));observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);return null}
