const KEY='meu-video-studio-ai:projects:v2'
type Media={id:string;name:string;kind:'video'|'image'|'audio';url:string;duration:number}
type Clip={id:string;assetId:string;start:number;duration:number;track:'video'|'audio';lane?:number;x?:number;y?:number;width?:number;height?:number;rotation?:number;flipX?:boolean}
type Project={id:string;media:Media[];clips:Clip[];playhead:number}
type T={x:number;y:number;width:number;height:number;rotation:number;flipX:boolean}
type D={id:string;mode:'move'|'resize';handle:string;px:number;py:number;t:T}
const MIN=0,MAX=200,POS_MIN=-200,POS_MAX=300,ZTOP=10000,ZSTEP=100
let stageRef:HTMLElement|null=null,rootRef:HTMLElement|null=null,ctrl:HTMLElement|null=null,drag:D|null=null,selected:string|null=null,raf=0,sig=''
const n=(v:unknown,d=0)=>Number.isFinite(Number(v))?Number(v):d
const cl=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v))
function pid(){return location.pathname.match(/\/editor\/([^/]+)/)?.[1]||null}
function read():Project|null{try{const id=pid();if(!id)return null;return (JSON.parse(localStorage.getItem(KEY)||'[]')as Project[]).find(p=>p.id===id)||null}catch{return null}}
function asset(p:Project,id:string){return p.media.find(m=>m.id===id)}
function active(p:Project,t:number){return p.clips.filter(c=>c.track==='video'&&t>=n(c.start)&&t<n(c.start)+Math.max(0,n(c.duration))).sort((a,b)=>n(a.lane)-n(b.lane)||n(a.start)-n(b.start)||a.id.localeCompare(b.id))}
function tr(c:Clip,i:number):T{const w=cl(n(c.width,i?55:100),MIN,MAX),h=cl(n(c.height,i?55:100),MIN,MAX);return{x:n(c.x,(100-w)/2),y:n(c.y,(100-h)/2),width:w,height:h,rotation:n(c.rotation),flipX:!!c.flipX}}
function apply(el:HTMLElement,t:T){el.style.left=t.x+'%';el.style.top=t.y+'%';el.style.width=t.width+'%';el.style.height=t.height+'%';el.style.transform=`rotate(${t.rotation}deg) scaleX(${t.flipX?-1:1})`}
function save(id:string,patch:Partial<Clip>){const p=read();if(!p)return;const all=JSON.parse(localStorage.getItem(KEY)||'[]')as Project[];localStorage.setItem(KEY,JSON.stringify(all.map(x=>x.id===p.id?{...x,clips:x.clips.map(c=>c.id===id?{...c,...patch}:c),updatedAt:new Date().toISOString()}:x)));sig='';window.dispatchEvent(new CustomEvent('vfs-project-changed'))}
function styles(){if(document.querySelector('[data-vfs-v5]'))return;const s=document.createElement('style');s.dataset.vfsV5='1';s.textContent=`.v5-root{position:absolute!important;inset:0!important;z-index:100!important;pointer-events:none!important}.v5-layer{position:absolute!important;box-sizing:border-box!important;pointer-events:none!important;user-select:none!important;transform-origin:center center!important}.v5-layer.sel{outline:2px solid #a78bfa!important;box-shadow:0 0 0 1px rgba(167,139,250,.25)!important}.v5-media{position:absolute!important;inset:0!important;overflow:hidden!important;pointer-events:none!important}.v5-media img,.v5-media video{display:block!important;width:100%!important;height:100%!important;object-fit:fill!important;pointer-events:none!important}.v5-h{position:absolute!important;width:12px!important;height:12px!important;border:2px solid #fff!important;background:#7c3aed!important;border-radius:3px!important;box-shadow:0 1px 4px #000!important;pointer-events:none!important}.v5-h.nw{left:-7px;top:-7px}.v5-h.n{left:50%;top:-7px;transform:translateX(-50%)}.v5-h.ne{right:-7px;top:-7px}.v5-h.e{right:-7px;top:50%;transform:translateY(-50%)}.v5-h.se{right:-7px;bottom:-7px}.v5-h.s{left:50%;bottom:-7px;transform:translateX(-50%)}.v5-h.sw{left:-7px;bottom:-7px}.v5-h.w{left:-7px;top:50%;transform:translateY(-50%)}.v5-controls{position:fixed;right:18px;top:88px;width:270px;background:rgba(16,16,20,.98);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:12px;z-index:999999;color:#fff;font:12px Inter,system-ui,sans-serif;box-shadow:0 18px 50px rgba(0,0,0,.45)}.v5-controls h4{margin:0 0 5px;font-size:12px}.v5-controls small{display:block;color:#8b8b95;margin-bottom:10px}.v5-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.v5-grid label{display:grid;gap:4px;font-size:9px;color:#aaa}.v5-controls input[type=number]{width:100%;height:30px;background:#0a0a0d;color:#fff;border:1px solid #2b2b32;border-radius:7px;padding:0 8px;box-sizing:border-box}.v5-range{grid-column:1/-1;display:grid;grid-template-columns:52px 1fr 48px;gap:7px;align-items:center}.v5-range output{height:28px;display:grid;place-items:center;background:#0a0a0d;border:1px solid #2b2b32;border-radius:7px}.v5-controls button{margin-top:8px;width:49%;height:30px;background:#17171d;color:#ddd;border:1px solid #2b2b32;border-radius:7px}.v5-controls button+button{margin-left:2%}`;document.head.appendChild(s)}
function controls(p:Project,c:Clip){if(!ctrl){ctrl=document.createElement('div');ctrl.className='v5-controls';document.body.appendChild(ctrl)}const i=active(p,n(p.playhead)).findIndex(x=>x.id===c.id);const t=tr(c,Math.max(0,i));ctrl.style.display='block';ctrl.innerHTML=`<h4>Transformação</h4><small>${asset(p,c.assetId)?.name||'Mídia'} · 0–200%</small><div class="v5-grid"><label>X (%)<input data-k=x type=number min=-200 max=300 step=.1 value=${t.x}></label><label>Y (%)<input data-k=y type=number min=-200 max=300 step=.1 value=${t.y}></label><div class="v5-range"><span>Largura</span><input data-k=w type=range min=0 max=200 step=1 value=${t.width}><output>${Math.round(t.width)}%</output></div><div class="v5-range"><span>Altura</span><input data-k=h type=range min=0 max=200 step=1 value=${t.height}><output>${Math.round(t.height)}%</output></div><label>Largura (%)<input data-k=wn type=number min=0 max=200 step=.1 value=${t.width}></label><label>Altura (%)<input data-k=hn type=number min=0 max=200 step=.1 value=${t.height}></label><label>Rotação (°)<input data-k=r type=number min=-360 max=360 value=${t.rotation}></label></div><button data-a=mirror>Espelhar</button><button data-a=reset>Resetar</button>`;ctrl.querySelectorAll<HTMLInputElement>('input[data-k]').forEach(inp=>inp.addEventListener('input',()=>{const p2=read();if(!p2)return;const k=inp.dataset.k||'',v=n(inp.value);if(k==='x')save(c.id,{x:cl(v,POS_MIN,POS_MAX)});if(k==='y')save(c.id,{y:cl(v,POS_MIN,POS_MAX)});if(k==='w'||k==='wn')save(c.id,{width:cl(v,MIN,MAX)});if(k==='h'||k==='hn')save(c.id,{height:cl(v,MIN,MAX)});if(k==='r')save(c.id,{rotation:cl(v,-360,360)});if(k==='w'||k==='wn'||k==='h'||k==='hn'){const o=inp.parentElement?.querySelector('output');if(o)o.textContent=Math.round(cl(v,MIN,MAX))+'%'}}));ctrl.querySelector('[data-a=mirror]')?.addEventListener('click',()=>{const p2=read();const x=p2?.clips.find(v=>v.id===c.id)?.flipX;if(p2)save(c.id,{flipX:!x})});ctrl.querySelector('[data-a=reset]')?.addEventListener('click',()=>save(c.id,{x:0,y:0,width:100,height:100,rotation:0,flipX:false}))}
function hit(stage:HTMLElement,x:number,y:number){return Array.from(stage.querySelectorAll<HTMLElement>('.v5-layer')).filter(l=>{const r=l.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}).sort((a,b)=>n(b.style.zIndex)-n(a.style.zIndex))}
function handleHit(stage:HTMLElement,x:number,y:number){if(!selected)return null;const layer=stage.querySelector<HTMLElement>(`.v5-layer[data-id="${selected}"]`);if(!layer)return null;for(const h of Array.from(layer.querySelectorAll<HTMLElement>('.v5-h'))){if(h.style.display==='none')continue;const r=h.getBoundingClientRect();if(x>=r.left-6&&x<=r.right+6&&y>=r.top-6&&y<=r.bottom+6)return h.dataset.h||null}return null}
function down(stage:HTMLElement,e:PointerEvent){if(e.button!==0||e.target instanceof HTMLInput||e.target instanceof HTMLButton)return;const p=read();if(!p)return;const clips=active(p,n(p.playhead));const h=handleHit(stage,e.clientX,e.clientY);if(h&&selected){const c=p.clips.find(x=>x.id===selected);if(!c)return;const i=Math.max(0,clips.findIndex(x=>x.id===c.id));drag={id:c.id,mode:'resize',handle:h,px:e.clientX,py:e.clientY,t:tr(c,i)};e.preventDefault();e.stopPropagation();return}const layers=hit(stage,e.clientX,e.clientY);if(!layers.length)return;const id=layers[0].dataset.id;if(!id)return;selected=id;updateSelection();const c=p.clips.find(x=>x.id===id);if(c){const i=Math.max(0,clips.findIndex(x=>x.id===id));controls(p,c);drag={id,mode:'move',handle:'',px:e.clientX,py:e.clientY,t:tr(c,i)}}e.preventDefault();e.stopPropagation()}
function move(stage:HTMLElement,e:PointerEvent){if(!drag)return;const dx=(e.clientX-drag.px)/Math.max(1,stage.clientWidth)*100,dy=(e.clientY-drag.py)/Math.max(1,stage.clientHeight)*100;let t={...drag.t};if(drag.mode==='move'){t.x=cl(t.x+dx,POS_MIN,POS_MAX);t.y=cl(t.y+dy,POS_MIN,POS_MAX)}else{let l=t.x,r=t.x+t.width,top=t.y,b=t.y+t.height;const h=drag.handle;if(h.includes('w'))l+=dx;if(h.includes('e'))r+=dx;if(h.includes('n'))top+=dy;if(h.includes('s'))b+=dy;const w=cl(r-l,MIN,MAX),hh=cl(b-top,MIN,MAX);if(h.includes('w'))l=r-w;if(h.includes('n'))top=b-h;t={...t,x:l,y:top,width:w,height:hh}}const layer=rootRef?.querySelector<HTMLElement>(`.v5-layer[data-id="${drag.id}"]`);if(layer)apply(layer,t);save(drag.id,{x:t.x,y:t.y,width:t.width,height:t.height})}
function up(){drag=null;sig='';rebuild()}
function updateSelection(){rootRef?.querySelectorAll<HTMLElement>('.v5-layer').forEach(l=>{const on=l.dataset.id===selected;l.classList.toggle('sel',on);l.querySelectorAll<HTMLElement>('.v5-h').forEach(h=>h.style.display=on?'block':'none')})}
function rebuild(){styles();const stage=document.querySelector<HTMLElement>('.video-stage'),p=read();if(!stage||!p)return;stageRef=stage;let root=stage.querySelector<HTMLElement>(':scope>.v5-root');if(!root){root=document.createElement('div');root.className='v5-root';stage.appendChild(root)}rootRef=root;bindStage(stage);const clips=active(p,n(p.playhead)),key=stage.dataset.v5id+'|'+n(p.playhead)+'|'+p.media.map(m=>m.id+':'+m.url).join('|')+'|'+clips.map(c=>c.id+':'+c.assetId+':'+c.start+':'+c.duration+':'+(c.lane??0)+':'+c.x+':'+c.y+':'+c.width+':'+c.height+':'+c.rotation+':'+c.flipX).join('|');if(key===sig&&root.children.length)return;sig=key;root.replaceChildren();stage.querySelectorAll<HTMLElement>(':scope>video,:scope>img').forEach(x=>x.style.visibility=clips.length?'hidden':'visible');clips.forEach((c,i)=>{const m=asset(p,c.assetId);if(!m||!['image','video'].includes(m.kind))return;const l=document.createElement('div');l.className='v5-layer'+(c.id===selected?' sel':'');l.dataset.id=c.id;apply(l,tr(c,i));l.style.zIndex=String(ZTOP-n(c.lane)*ZSTEP+i);const box=document.createElement('div');box.className='v5-media';const el=m.kind==='image'?document.createElement('img'):document.createElement('video');el.src=m.url;el.draggable=false;el.addEventListener('error',()=>{const fresh=read();const mm=fresh?asset(fresh,c.assetId):null;if(mm?.url&&mm.url!==el.src){el.src=mm.url;sig=''}});if(el instanceof HTMLVideoElement){el.muted=true;el.playsInline=true;el.preload='auto';try{el.currentTime=Math.max(0,n(p.playhead)-n(c.start))}catch{}}box.appendChild(el);l.appendChild(box);['nw','n','ne','e','se','s','sw','w'].forEach(h=>{const q=document.createElement('div');q.className='v5-h '+h;q.dataset.h=h;q.style.display=c.id===selected?'block':'none';l.appendChild(q)});root.appendChild(l)});if(selected){const c=p.clips.find(x=>x.id===selected);if(c)controls(p,c)}updateSelection()}
let bound:HTMLElement|null=null
function bindStage(stage:HTMLElement){if(bound===stage)return;bound=stage;stage.dataset.v5id=stage.dataset.v5id||Math.random().toString(36).slice(2);stage.addEventListener('pointerdown',e=>down(stage,e as PointerEvent),true);stage.addEventListener('pointermove',e=>move(stage,e as PointerEvent),true);stage.addEventListener('pointerup',up,true);stage.addEventListener('pointercancel',up,true)}
function sync(){rebuild();raf=requestAnimationFrame(sync)}
window.addEventListener('storage',()=>{sig='';rebuild()});window.addEventListener('vfs-project-changed',()=>{sig='';rebuild()});window.addEventListener('popstate',()=>{sig='';rebuild()});window.addEventListener('beforeunload',()=>cancelAnimationFrame(raf));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{rebuild();raf=requestAnimationFrame(sync)},{once:true});else{rebuild();raf=requestAnimationFrame(sync)}
