const PROJECTS_KEY = 'meu-video-studio-ai:projects:v2'

type Media = { id:string; name:string; kind:'video'|'image'|'audio'; url:string; duration:number }
type Clip = { id:string; assetId:string; start:number; duration:number; track:'video'|'audio'; lane?:number; x?:number; y?:number; width?:number; height?:number; rotation?:number; flipX?:boolean }
type Project = { id:string; media:Media[]; clips:Clip[]; playhead:number }
type Transform = { x:number; y:number; width:number; height:number; rotation:number; flipX:boolean }

const MAX_SIZE = 200
const MIN_SIZE = 1

const CSS = `
.vfs-layer-compositor{position:absolute!important;inset:0!important;overflow:visible!important;z-index:50!important;pointer-events:none!important}
.vfs-layer{position:absolute;box-sizing:border-box;overflow:visible;pointer-events:auto;cursor:move;user-select:none;touch-action:none;transform-origin:center center}
.vfs-layer-media{position:absolute;inset:0;overflow:hidden;border-radius:1px}
.vfs-layer img,.vfs-layer video{display:block!important;width:100%!important;height:100%!important;object-fit:fill!important;pointer-events:none!important;user-select:none!important}
.vfs-layer.vfs-selected{outline:2px solid #a78bfa;box-shadow:0 0 0 1px rgba(167,139,250,.25),0 0 22px rgba(124,58,237,.18)}
.vfs-handle{position:absolute;width:12px;height:12px;border:2px solid #fff;background:#7c3aed;border-radius:3px;z-index:5;box-shadow:0 1px 4px #000;pointer-events:auto}
.vfs-handle.nw{left:-7px;top:-7px;cursor:nwse-resize}.vfs-handle.n{left:50%;top:-7px;transform:translateX(-50%);cursor:ns-resize}.vfs-handle.ne{right:-7px;top:-7px;cursor:nesw-resize}.vfs-handle.e{right:-7px;top:50%;transform:translateY(-50%);cursor:ew-resize}.vfs-handle.se{right:-7px;bottom:-7px;cursor:nwse-resize}.vfs-handle.s{left:50%;bottom:-7px;transform:translateX(-50%);cursor:ns-resize}.vfs-handle.sw{left:-7px;bottom:-7px;cursor:nesw-resize}.vfs-handle.w{left:-7px;top:50%;transform:translateY(-50%);cursor:ew-resize}
.vfs-layer-badge{position:absolute;left:6px;top:6px;background:rgba(0,0,0,.7);color:#fff;padding:3px 6px;border-radius:5px;font:600 9px/1 Inter,system-ui,sans-serif;z-index:6;pointer-events:none}
.vfs-layer-controls{position:fixed;right:18px;top:88px;width:280px;background:rgba(16,16,20,.98);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:12px;z-index:99999;color:#fff;font:12px Inter,system-ui,sans-serif;box-shadow:0 18px 50px rgba(0,0,0,.45)}
.vfs-layer-controls h4{margin:0 0 5px;font-size:12px}.vfs-layer-controls .sub{display:block;color:#6d6e78;font-size:9px;margin-bottom:10px}.vfs-layer-controls .grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.vfs-layer-controls label{display:grid;gap:4px;font-size:9px;color:#90909a}.vfs-layer-controls input[type=number]{width:100%;height:30px;background:#0a0a0d;color:#fff;border:1px solid rgba(255,255,255,.1);border-radius:7px;padding:0 8px;outline:0}.vfs-layer-controls input[type=range]{width:100%;height:22px}.vfs-size-title{grid-column:1/-1;color:#bdbdc7;font-size:10px;margin-top:2px}.vfs-range-row{grid-column:1/-1;display:grid;grid-template-columns:52px 1fr 52px;gap:7px;align-items:center}.vfs-range-row span{font-size:9px;color:#777883}.vfs-range-row output{height:28px;display:grid;place-items:center;background:#0a0a0d;border:1px solid rgba(255,255,255,.1);border-radius:7px;font-size:9px;color:#ddd}.vfs-layer-controls .row{display:flex;gap:6px;margin-top:8px}.vfs-layer-controls button{flex:1;height:30px;border:1px solid rgba(255,255,255,.1);border-radius:7px;background:#17171d;color:#ddd;cursor:pointer}.vfs-layer-controls button:hover{background:#22222a;color:#fff}.vfs-layer-controls .primary{background:#6d28d9;border-color:#8b5cf6}.vfs-layer-hint{position:absolute;left:50%;bottom:8px;transform:translateX(-50%);background:rgba(0,0,0,.68);color:#bfc0ca;padding:5px 8px;border-radius:7px;font:10px Inter,system-ui,sans-serif;z-index:60;pointer-events:none;white-space:nowrap}
`

let styleInjected = false
let selectedClipId: string | null = null
let activeStage: HTMLElement | null = null
let controlEl: HTMLElement | null = null
let lastRenderedTime = -1
let renderQueued = false

function injectCss(){if(styleInjected)return;const s=document.createElement('style');s.textContent=CSS;document.head.appendChild(s);styleInjected=true}
function projectId(){const m=location.pathname.match(/\/editor\/([^/]+)/);return m?.[1]??null}
function readProject():Project|null{try{const all=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]') as Project[];const id=projectId();return all.find(p=>p.id===id)||null}catch{return null}}
function writeProject(project:Project){try{const all=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]') as Project[];const raw=JSON.stringify(all.map(p=>p.id===project.id?project:p));localStorage.setItem(PROJECTS_KEY,raw);window.dispatchEvent(new StorageEvent('storage',{key:PROJECTS_KEY,newValue:raw}))}catch{}}
function assetFor(p:Project,id:string){return p.media.find(m=>m.id===id)}
function stageElement(){return document.querySelector<HTMLElement>('.video-stage')}
function clamp(v:number,min:number,max:number){return Math.max(min,Math.min(max,v))}
function getTransform(c:Clip,index:number):Transform{const width=clamp(Number.isFinite(c.width)?Number(c.width):(index===0?100:55),MIN_SIZE,MAX_SIZE);const height=clamp(Number.isFinite(c.height)?Number(c.height):(index===0?100:55),MIN_SIZE,MAX_SIZE);return{x:Number.isFinite(c.x)?Number(c.x):((100-width)/2),y:Number.isFinite(c.y)?Number(c.y):((100-height)/2),width,height,rotation:Number(c.rotation||0),flipX:Boolean(c.flipX)}}
function activeVideoClips(p:Project,t:number){return p.clips.filter(c=>c.track==='video'&&t>=Number(c.start||0)&&t<Number(c.start||0)+Number(c.duration||0)).sort((a,b)=>(a.lane??0)-(b.lane??0))}
function applyTransform(el:HTMLElement,t:Transform){el.style.left=`${t.x}%`;el.style.top=`${t.y}%`;el.style.width=`${t.width}%`;el.style.height=`${t.height}%`;el.style.transform=`rotate(${t.rotation}deg) scaleX(${t.flipX?-1:1})`}
function updateClip(project:Project,id:string,patch:Partial<Clip>,rerender=true){const next={...project,clips:project.clips.map(c=>c.id===id?{...c,...patch}:c),updatedAt:new Date().toISOString()} as Project;writeProject(next);if(rerender)scheduleRender();return next}
function scheduleRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;render()})}
function ensureControls(){if(controlEl)return controlEl;controlEl=document.createElement('div');controlEl.className='vfs-layer-controls';controlEl.style.display='none';document.body.appendChild(controlEl);return controlEl}
function renderControls(project:Project,clip:Clip,t:Transform){
 const el=ensureControls();el.style.display='block'
 el.innerHTML=`<h4>Camada selecionada</h4><span class="sub">${assetFor(project,clip.assetId)?.name||'Mídia'} · largura e altura independentes · 0–200%</span><div class="grid"><label>X (%)<input data-k="x" type="number" min="-200" max="200" step="0.1" value="${t.x.toFixed(1)}"></label><label>Y (%)<input data-k="y" type="number" min="-200" max="200" step="0.1" value="${t.y.toFixed(1)}"></label><div class="vfs-size-title">Tamanho da camada</div><div class="vfs-range-row"><span>Largura</span><input data-k="widthRange" type="range" min="0" max="200" step="1" value="${t.width}"><output data-out="width">${Math.round(t.width)}%</output></div><div class="vfs-range-row"><span>Altura</span><input data-k="heightRange" type="range" min="0" max="200" step="1" value="${t.height}"><output data-out="height">${Math.round(t.height)}%</output></div><label>Largura (%)<input data-k="width" type="number" min="0" max="200" step="0.1" value="${t.width.toFixed(1)}"></label><label>Altura (%)<input data-k="height" type="number" min="0" max="200" step="0.1" value="${t.height.toFixed(1)}"></label><label>Rotação (°)<input data-k="rotation" type="number" min="-360" max="360" step="1" value="${t.rotation.toFixed(0)}"></label><label>Camada<input data-k="lane" type="number" min="0" max="20" step="1" value="${clip.lane??0}"></label></div><div class="row"><button data-action="front" class="primary">Trazer para frente</button><button data-action="back">Enviar para trás</button></div><div class="row"><button data-action="mirror">Espelhar</button><button data-action="reset">Resetar</button></div>`
 const set=(key:keyof Clip,value:number)=>{const patch:Partial<Clip>={};(patch as any)[key]=value;const p=readProject();if(p)updateClip(p,clip.id,patch,true)}
 el.querySelectorAll<HTMLInputElement>('input[data-k]').forEach(input=>input.addEventListener('input',()=>{const key=input.dataset.k!;const value=Number(input.value);if(!Number.isFinite(value))return;if(key==='widthRange'){const v=clamp(value,0,200);input.parentElement?.querySelector('output')?.replaceChildren(document.createTextNode(`${Math.round(v)}%`));set('width',v)}else if(key==='heightRange'){const v=clamp(value,0,200);input.parentElement?.querySelector('output')?.replaceChildren(document.createTextNode(`${Math.round(v)}%`));set('height',v)}else if(key==='width')set('width',clamp(value,0,200));else if(key==='height')set('height',clamp(value,0,200));else if(key==='x')set('x',clamp(value,-200,200));else if(key==='y')set('y',clamp(value,-200,200));else if(key==='rotation')set('rotation',clamp(value,-360,360));else if(key==='lane')set('lane',clamp(Math.round(value),0,20))}))
 el.querySelector('[data-action="front"]')?.addEventListener('click',()=>{const p=readProject();if(!p)return;const maxLane=Math.max(...p.clips.filter(c=>c.track==='video').map(c=>c.lane??0),0);updateClip(p,clip.id,{lane:maxLane+1})})
 el.querySelector('[data-action="back"]')?.addEventListener('click',()=>{const p=readProject();if(p)updateClip(p,clip.id,{lane:0})})
 el.querySelector('[data-action="mirror"]')?.addEventListener('click',()=>{const p=readProject();if(p)updateClip(p,clip.id,{flipX:!t.flipX})})
 el.querySelector('[data-action="reset"]')?.addEventListener('click',()=>{const p=readProject();if(p)updateClip(p,clip.id,{x:0,y:0,width:100,height:100,rotation:0,flipX:false})})
}
function beginMove(layer:HTMLElement,project:Project,clip:Clip,index:number,stage:HTMLElement,ev:PointerEvent){selectedClipId=clip.id;const start=getTransform(clip,index),sx=ev.clientX,sy=ev.clientY;layer.setPointerCapture(ev.pointerId);const move=(e:PointerEvent)=>{const dx=(e.clientX-sx)/stage.clientWidth*100,dy=(e.clientY-sy)/stage.clientHeight*100;const next={...start,x:clamp(start.x+dx,-MAX_SIZE,100),y:clamp(start.y+dy,-MAX_SIZE,100)};applyTransform(layer,next);const p=readProject()||project;updateClip(p,clip.id,{x:next.x,y:next.y},false)};const up=()=>{layer.releasePointerCapture(ev.pointerId);layer.removeEventListener('pointermove',move);layer.removeEventListener('pointerup',up);scheduleRender()};layer.addEventListener('pointermove',move);layer.addEventListener('pointerup',up)}
function beginResize(layer:HTMLElement,project:Project,clip:Clip,index:number,stage:HTMLElement,ev:PointerEvent,dir:string){selectedClipId=clip.id;const start=getTransform(clip,index),sx=ev.clientX,sy=ev.clientY;layer.setPointerCapture(ev.pointerId);const move=(e:PointerEvent)=>{const dx=(e.clientX-sx)/stage.clientWidth*100,dy=(e.clientY-sy)/stage.clientHeight*100;let left=start.x,top=start.y,right=start.x+start.width,bottom=start.y+start.height;if(dir.includes('w'))left=clamp(start.x+dx,100-MAX_SIZE,start.x+start.width-MIN_SIZE);if(dir.includes('e'))right=clamp(start.x+start.width+dx,start.x+MIN_SIZE,MAX_SIZE);if(dir.includes('n'))top=clamp(start.y+dy,100-MAX_SIZE,start.y+start.height-MIN_SIZE);if(dir.includes('s'))bottom=clamp(start.y+start.height+dy,start.y+MIN_SIZE,MAX_SIZE);const next={...start,x:left,y:top,width:clamp(right-left,MIN_SIZE,MAX_SIZE),height:clamp(bottom-top,MIN_SIZE,MAX_SIZE)};applyTransform(layer,next);const p=readProject()||project;updateClip(p,clip.id,{x:next.x,y:next.y,width:next.width,height:next.height},false)};const up=()=>{layer.releasePointerCapture(ev.pointerId);layer.removeEventListener('pointermove',move);layer.removeEventListener('pointerup',up);scheduleRender()};layer.addEventListener('pointermove',move);layer.addEventListener('pointerup',up)}
function bindLayer(layer:HTMLElement,project:Project,clip:Clip,index:number,stage:HTMLElement){layer.addEventListener('pointerdown',ev=>{const e=ev as PointerEvent;const target=e.target as HTMLElement;if(target.classList.contains('vfs-handle'))return;e.preventDefault();beginMove(layer,project,clip,index,stage,e)});layer.querySelectorAll<HTMLElement>('.vfs-handle').forEach(handle=>handle.addEventListener('pointerdown',ev=>{const e=ev as PointerEvent;e.stopPropagation();e.preventDefault();beginResize(layer,project,clip,index,stage,e,handle.dataset.dir||'se')}))}
function render(){const stage=stageElement(),p=readProject();if(!stage||!p)return;activeStage=stage;injectCss();const time=Number(p.playhead||0);lastRenderedTime=time;stage.style.position='relative';stage.style.overflow='hidden';let comp=stage.querySelector<HTMLElement>('.vfs-layer-compositor');if(!comp){comp=document.createElement('div');comp.className='vfs-layer-compositor';stage.appendChild(comp)}comp.innerHTML='';stage.querySelectorAll(':scope > video, :scope > img').forEach(el=>(el as HTMLElement).style.visibility='hidden');const clips=activeVideoClips(p,time);clips.forEach((clip,index)=>{const asset=assetFor(p,clip.assetId);if(!asset)return;const layer=document.createElement('div');layer.className=`vfs-layer${clip.id===selectedClipId?' vfs-selected':''}`;layer.dataset.clipId=clip.id;const tr=getTransform(clip,index);applyTransform(layer,tr);layer.style.zIndex=String(100+(clip.lane??0)*10+index);const mediaWrap=document.createElement('div');mediaWrap.className='vfs-layer-media';const media=asset.kind==='image'?document.createElement('img'):document.createElement('video');media.src=asset.url;media.draggable=false;if(media instanceof HTMLVideoElement){media.muted=true;media.playsInline=true;media.preload='auto';try{media.currentTime=Math.max(0,time-clip.start)}catch{}}mediaWrap.appendChild(media);layer.appendChild(mediaWrap);const badge=document.createElement('div');badge.className='vfs-layer-badge';badge.textContent=`Camada ${(clip.lane??0)+1}`;layer.appendChild(badge);(['nw','n','ne','e','se','s','sw','w'] as const).forEach(dir=>{const h=document.createElement('div');h.className=`vfs-handle ${dir}`;h.dataset.dir=dir;if(clip.id!==selectedClipId)h.style.display='none';layer.appendChild(h)});bindLayer(layer,p,clip,index,stage);comp.appendChild(layer);if(clip.id===selectedClipId)renderControls(p,clip,tr)});if(selectedClipId&&!clips.some(c=>c.id===selectedClipId)){selectedClipId=null;if(controlEl)controlEl.style.display='none'}if(clips.length>1||selectedClipId){const hint=document.createElement('div');hint.className='vfs-layer-hint';hint.textContent=clips.length>1?'Camadas sobrepostas · cada mídia pode ter 0–200% de largura e altura':'Clique na mídia · 8 pontos para redimensionar independentemente';comp.appendChild(hint)}}
function syncTime(){const p=readProject();if(!p)return;const t=Number(p.playhead||0);if(t!==lastRenderedTime)scheduleRender()}
function boot(){injectCss();scheduleRender()}
new MutationObserver(()=>{const stage=document.querySelector('.video-stage');if(stage&&stage!==activeStage){activeStage=stage;setTimeout(boot,20)}}).observe(document.body,{childList:true,subtree:true})
window.addEventListener('popstate',()=>setTimeout(boot,50))
window.addEventListener('storage',()=>scheduleRender())
setInterval(syncTime,150)
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()
